Skip documentation changes in Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,6 +26,17 @@ cache:
 install:
   - make install_requirements
 
+_skip_documentation_changes: &skip_documentation_changes |-
+  echo $TRAVIS_COMMIT_RANGE
+  if [[ $(git diff --exit-code --quiet --name-only $TRAVIS_COMMIT_RANGE 2>/dev/null) -eq 1 ]]; then
+    if ! $(git diff --name-only $TRAVIS_COMMIT_RANGE) | grep -qvE '(.md$)'; then
+      echo "Documentation-only update detected, not running CI"
+      travis_terminate 0
+    fi
+  else
+    echo "Travis commit range invalid, running CI"
+  fi
+  
 _install_cf_cli_and_local: &install_cf_cli_and_local |-
   wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
   echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
@@ -40,9 +51,12 @@ _get_host: &get_host |-
 jobs:
   include:
     - stage: build
+      before_install:
+        - *skip_documentation_changes
       script: make lint test_unit build
     - stage: test
       before_install:
+        - *skip_documentation_changes
         - *install_cf_cli_and_local
       before_script:
         - *get_host
@@ -55,6 +69,7 @@ jobs:
         - sleep 5
     - stage: test
       before_install:
+        - *skip_documentation_changes
         - *install_cf_cli_and_local
       before_script:
         - *get_host
@@ -67,6 +82,7 @@ jobs:
         - sleep 5
     - stage: test
       before_install:
+        - *skip_documentation_changes
         - *install_cf_cli_and_local
       before_script:
         - *get_host
@@ -79,6 +95,7 @@ jobs:
         - sleep 5
     - stage: test
       before_install:
+        - *skip_documentation_changes
         - *install_cf_cli_and_local
       before_script:
         - *get_host
